### ISSUE TITLE
hello, I wanted to contact you but I don't know how, so I will leave my message here and delete it later after your respond

### ISSUE THREAD

**Issue by Aleksyeus** [keiveulbugs/Dexscreener_pricebot#2]
can you create a tool that will watch gmgn.ai coins(if not possible, dexscreener)? to be able apply filters such as market cap and etc and to check if any token increased 1% and then it output in console or send on webhook of discord? so that I will have this running for hours. I will be more than thankful! if you leave your discord, I will contact you

**Comment by keiveulbugs** [comment]
Hi Aleksyeus,

GMGN.ai does not have an API that is able to do this as far as I am understanding their documentation.
For dexscreener, this is indeed possible. However, it requires quite some additional work. Unfortunately, I won't be able to afford free time to develop it at no cost. If you are interested in potentially hiring me, feel free to drop your discord and I will send you a message. 

Kind regards,
